import type { Metadata } from "next";
import "../styles/globals.css";
import "../styles/_colors.scss";
import { ConvexAuthProvider } from "@convex-dev/auth/react";
import { convex } from "@/lib/convexClient";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "sonner";
import styles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.layout}>
        <ConvexAuthProvider client={convex}>
          <Header />
          {children}
          <Footer />
          <Toaster
            theme="light"
            richColors
            toastOptions={{
              style: {
                background: "white",
                color: "black",
                border: "1px solid #e5e7eb",
              },
              className: styles.toastCustom,
            }}
          />
        </ConvexAuthProvider>
      </body>
    </html>
  );
}
