import type { Metadata } from "next";
import "./globals.css";
import { ConvexAuthProvider } from "@convex-dev/auth/react";
import { convex } from "@/lib/convexClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConvexAuthProvider client={convex}>{children}</ConvexAuthProvider>
      </body>
    </html>
  );
}
