import type { Metadata } from "next";
import "../styles/globals.css";
import { ConvexAuthProvider } from "@convex-dev/auth/react";
import { convex } from "@/lib/convexClient";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ConvexAuthProvider client={convex}>
            <Header />
            {children}
            <Footer />
            <Toaster
              theme="light"
              richColors
              toastOptions={{
                style: {
                  background: "white",
                  color: "black",
                  border: "1px solid #e5e7eb",
                },
                className: "toast-custom",
              }}
            />
          </ConvexAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
